# Generated by Django 4.2.1 on 2023-05-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesdb",
            name="sales",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
